### ISSUE TITLE
CUDA 11.0 ++

### ISSUE THREAD

**Issue by chandlerbing65nm** [jbwang1997/OBBDetection#77]
Will this repo compile with cuda 11.0 and above?

**Comment by jbwang1997** [comment]
This repo can be compiled with Cuda 11.0.

**Comment by houw0517** [comment]
Can you write a description of the document about the steps of compiling and training ？After compiling problem was resolved by Cuda 11.0 . It also appears that runtimeError: CUDA error: no kernel image is available for execution on the device
